apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::202417427750:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::202417427750:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1P8FUT7IXL9OQ
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-04T20:22:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1556"
  uid: df002dd8-5d53-4f47-836f-cb3a9b4aacc1
